# These are supported funding model platforms

github: [peci1]
#custom: ["bitcoin:1CQEGaeP8k6TftvJjEwo59iSktBefeVArc?label=peci1&message=Github%20Sponsors%20nvidia-htop"]
custom: ["https://btc.com/1CQEGaeP8k6TftvJjEwo59iSktBefeVArc"]